name: GitHub Skyline
on:
  schedule:
  # Runs at 12 am  '0 0 * * *'  UTC
  - cron: '1 0 * * *'
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Genrate Skyline
        uses: lowlighter/metrics@master
        with:
          filename: images/skyline.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # GitHub Skyline
          plugin_skyline: yes
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1
          base: metadata
